# Site settings
title: giatro.me
motto: "Gianluca Troiani: technologist, writer, engineer, developer, maker. On my work, hacks and tips."
email: gianluca.troiani@gmail.com
description: "Gianluca Troiani's personal site: my work, hacks and tips"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://giatro.me" # the base hostname & protocol for your site
# url: "http://localhost:4000" # the base hostname & protocol for your site
twitter_username: giatro
github_username:  giatro
facebook_username: gianluca.troiani.12
googleplus_username: GianlucaTroiani
linkedin_id: pub/gianluca-troiani/33/9a9/415

# Build settings
markdown: kramdown
highlighter: pygments
excerpt_separator: "<!--more-->"
