# Site settings
title: giatro
motto: "Gianluca Troiani: technologist, writer, engineer, developer, hacker"
email: gianluca.troiani@gmail.com
description: "Gianluca Troiani's personal site: my work, hacks and tips"
baseurl: "" # the subpath of your site, e.g. /blog/
# url: "http://giatro.me" # the base hostname & protocol for your site
url: "http://localhost:4000" # the base hostname & protocol for your site
twitter_username: giatro
github_username:  giatro
facebook_username: gianluca.troiani.12
googleplus_username: GianlucaTroiani

# Build settings
markdown: kramdown
